[package]
name = "interpreter-in-rust"
version = "0.1.0"
edition = "2021"



[lib]
name = "monkey_lib"
path = "lib/monkey.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
